[rpi_pico2w]
extends = rp2040_base
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
;debug_tool = cmsis-dap
;upload_protocol = cmsis-dap
;debug_speed = 5000
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
build_flags = ${rp2040_base.build_flags}
    -I variants/rpi_pico2w
    -D PICO_RP2350
    -D RP2040_PLATFORM
    -D P_LORA_DIO_0=15
    -D P_LORA_DIO_1=14
    -D P_LORA_RESET=20
    -D P_LORA_NSS=17
    -D P_LORA_SCK=18
    -D P_LORA_MOSI=19
    -D P_LORA_MISO=16
    -D P_LORA_EN=13
    -D SX1276_CURRENT_LIMIT=130
    -D LORA_TX_POWER=17
    -D RADIO_CLASS=CustomSX1276
    -D WRAPPER_CLASS=CustomSX1276Wrapper
;    -D PIN_BOARD_SDA=8
;    -D PIN_BOARD_SCL=9
;    -D DISPLAY_CLASS=SSD1306Display
;    -D P_LORA_TX_LED=25
;    -D PIN_VBAT_READ=28

build_src_filter = ${rp2040_base.build_src_filter}
  +<Pico2WBoard.cpp>
  +<../variants/rpi_pico2w>
lib_deps = ${rp2040_base.lib_deps}
lib_ignore = 
  BLE
  WIFI

[env:Pico2W_repeater]
extends = rpi_pico2w
build_flags = ${rpi_pico2w.build_flags}
  -D ADVERT_NAME='"Pico2W-LoRa Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD = '"password"'
  -D MAX_NEIGHBOURS=50
; -D MESH_PACKET_LOGGING=1
; -D MESH_DEBUG=1
build_src_filter = ${rpi_pico2w.build_src_filter}
  +<../examples/simple_repeater>

[env:Pico2W_room_server]
extends = rpi_pico2w
build_flags = ${rpi_pico2w.build_flags}
  -D ADVERT_NAME='"RP2350-LoRa Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
  -D MESH_DEBUG=1
build_src_filter = ${rpi_pico2w.build_src_filter}
  +<../examples/simple_room_server>

[env:Pico2W_companion_radio_usb]
extends = rpi_pico2w
build_flags = ${rpi_pico2w.build_flags}
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=8
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${rpi_pico2w.build_src_filter}
  +<../examples/companion_radio/*.cpp>
lib_deps = ${rpi_pico2w.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Pico2W_companion_radio_ble]
extends = rpi_pico2w
build_flags = ${rpi_pico2w.build_flags}
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=8
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${rpi_picow.build_src_filter}
  +<../examples/companion_radio/*.cpp>
lib_deps = ${rpi_picow.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Pico2W_terminal_chat]
extends = rpi_pico2w
build_flags = ${rpi_pico2w.build_flags}
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${rpi_pico2w.build_src_filter}
  +<../examples/simple_secure_chat/main.cpp>
lib_deps = ${rpi_pico2w.lib_deps}
  densaugeo/base64 @ ~1.4.0